.approved {	
	background-color: orange;
	background-size: 10px;
	background-image: -webkit-linear-gradient(0, transparent 50%, rgba(255, 255, 255, .5) 25%);
	background-image: -moz-linear-gradient(0px 50%, transparent 50%, rgba(255, 255, 255, 0.5) 25%);
	background-image: -ms-linear-gradient(0, transparent 50%, rgba(255, 255, 255, .5) 25%);
	background-image: -o-linear-gradient(0, transparent 50%, rgba(255, 255, 255, .5) 25%);	
}	