    .Styling { 
    background-image: -moz-repeating-linear-gradient(-45deg, rgba(0, 0, 0, 0.5),
    rgba(0, 0, 0, 0.5) 12px, rgba(0, 0, 0, 0) 12px, rgba(0, 0, 0, 0) 15px);
    -moz-background-size: 22px 22px;
    background-image: -webkit-repeating-linear-gradient(-45deg, rgba(0, 0, 0, 0.5),
    rgba(0, 0, 0, 0.5) 12px, rgba(0, 0, 0, 0) 12px, rgba(0, 0, 0, 0) 15px);
    -webkit-background-size: 22px 22px;
    background-size: 22px 22px;
     }